### ISSUE TITLE
Runtimeerror: Can't start new thread

### ISSUE THREAD

**Issue by ghost** [Dendroidal/Jap-jap-definition-scraper-from-weblio--Anki-add-on-#3]
Getting this error when doing bulk fetch. Happens a bunch of times but I just copied one instance.

RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/1591861881/definition_inserter.py", line 136, in prepare
    thread.start()
  File "threading.py", line 852, in start

I also get a "flush" error, missing component. Will post when it happens.

**Comment by Dendroidal** [comment]
Hum... Since I don't actually use the bulk fetch feature myself, I really could use more data to figure out what the problem is.
Here are a few questions:

- About how many cards are you trying to fetch at once? (this could be an issue with the number of threads)
- Did you get this issue when trying to bulk fetch different groups of cards, or when trying to fetch the same group several times? (there could be a specific word causing trouble)

**Comment by ghost** [comment]
Both of your questios are correct. I tried doing many at once and although they're all in the same deck, they have different subdecks. Could be that that's problem then :/

**Comment by Dendroidal** [comment]
Well, if you keep running into this problem, try to get me a more detailed report and I'll look into it.

I've never run into this issue in my usage, so it's hard to judge the issue.
